services:
  - type: web
    name: hrms-backend
    runtime: node
    rootDir: HRMS/hr-dashboard/backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
